# resources.py
# Centralisation des textes de l'UI pour internationalisation

UI_TEXTS = {
    'daltonian_button': "Active le mode daltonien pour de meilleures couleurs d'accessibilité",
    'invert_boards_button': "Inverse l'affichage des boards joueur/IA pour l'accessibilité",
    'toggle_hp_button': "Affiche ou masque les barres de vie des unités et héros",
    'hero1_panel': "Statistiques détaillées de votre héros",
    'hero2_panel': "Statistiques détaillées du héros IA",
    'activate_hero_button': "Active le pouvoir spécial de votre héros (coût en mana indiqué)",
    'mana_label': "Votre mana disponible pour jouer des cartes ou activer des pouvoirs",
    'player_board': "Votre board : faites glisser ou cliquez sur vos unités pour attaquer",
    'ia_board_widget': "Board de l'IA : ciblez ces unités pour attaquer",
    'pv1_label': "Points de vie restants de votre héros",
    'pv2_label': "Points de vie restants du héros IA",
    'toggle_log_button': "Affiche ou masque le log du combat",
    'copy_log_button': "Copie l'intégralité du log dans le presse-papiers",
    'export_log_button': "Exporte le log du combat dans un fichier texte",
    'log': "Historique détaillé des actions du combat",
    'next_button': "Passer au tour suivant (raccourci : Entrée)",
    'forfeit_button': "Abandonner la partie et retourner au menu",
    'timer_label': "Temps restant pour jouer ce tour",
    # MainMenu
    'theme_combo': "Changer le thème (clair, sombre, contraste élevé)",
    'play_button': "Jouer (Raccourci : N)",
    'deck_button': "Decks (Raccourci : D)",
    'shop_button': "Boutique (Raccourci : B)",
    'collection_button': "Collection (Raccourci : C)",
    'profile_button': "Changer de joueur",
    'logout_button': "Déconnexion (Raccourci : R)",
    # DeckMenu
    'deck_selector': "Sélectionnez le slot de deck à éditer",
    'tabs': "Naviguez entre les onglets Héros, Unités et Cartes",
    'deck_list': "Liste des cartes actuellement dans le deck. Cliquez pour retirer.",
    'hero_preview': "Aperçu du héros sélectionné",
    'hero_list': "Liste des héros disponibles. Sélectionnez-en un pour l'ajouter au deck.",
    'choose_hero_button': "Ajoute le héros sélectionné au deck",
    'remove_hero_button': "Retire le héros du deck",
    'duplicate_button': "Dupliquer ce deck",
    'save_button': "Valider le deck",
    'back_button': "Retour au menu principal",
    # ShopMenu
    'shop_label': "Bienvenue dans la boutique. Achetez des boosters pour agrandir votre collection.",
    'unit_button': "Achetez un booster gratuit et obtenez de nouvelles cartes",
    'pack_button': "Achetez un pack de 5 boosters gratuits pour plus de cartes",
    'currency_label': "Votre monnaie actuelle pour les achats en boutique",
    'shop_stats_panel': "Détails de la dernière carte obtenue",
    'shop_card_widget': "Aperçu visuel de la dernière carte obtenue",
    'buy_button': "Acheter un booster pour 100 pièces",
    'shop_back_button': "Retour au menu principal",
    'history_button': "Afficher l'historique des boosters ouverts récemment",
    # PlayMenu
    'play_label': "Choisissez un mode de jeu.",
    'solo_button': "Lancez une partie solo contre l'IA",
    'multi_button': "Le mode multijoueur sera disponible prochainement",
    'deck_label': "Sélectionnez le deck à utiliser pour la partie",
    'deck_combo': "Choisissez un de vos decks pour jouer",
    'deck_cards_list': "Liste des cartes du deck sélectionné",
    'deck_summary_panel': "Résumé des statistiques du deck sélectionné",
    'deck_preview_panel': "Aperçu visuel du deck sélectionné",
    'reset_history_button': "Efface l'historique des parties jouées",
    'history_table': "Historique de vos parties précédentes",
    'play_play_button': "Jouer !",
    'play_back_button': "Retour",
    # CollectionMenu
    'collection_label': "Votre collection de cartes. Utilisez la barre de recherche ou les tris pour filtrer.",
    'search_bar': "Tapez pour rechercher une carte par nom",
    'sort_combo': "Choisissez un critère de tri : nom, rareté, coût",
    'sort_all_button': "Trier la collection par nom, rareté, coût ou nombre d'exemplaires",
    'cards_list': "Liste de toutes vos cartes. Sélectionnez-en une pour voir ses détails.",
    'collection_back_button': "Retour au menu principal",
    'collection_stats_panel': "Statistiques détaillées de la carte sélectionnée",
    'collection_card_widget': "Aperçu visuel de la carte sélectionnée",
} 